import React from "react";
import '/Users/lorenzocappiello/Desktop/portfolio 2023/src/Works.css';

function WorksSection() {

    return (
        <section id="works" className="works-section">
            <div className="my-works-1">
                <div className="my-works-content-1">
                    <p className="works-languages">
                    HTML - CSS - JavaScript - React.js
                    </p>
                    <h2 className="works-title">My Portfolio</h2>
                    <p className="works-info">
                    Personal website, created in HTML, CSS (Media Query e FlexBox), JavaScript 
                    and React.js, with the aim of collecting all the projects created so far. 
                    After thinking about the structure and studying a graphic on Figma that 
                    could be simple and effective, the final result was this.
                    </p>
                    <div className="works-button-div">
                        <a href="#">
                            <button className="works-button">Find out more ↘</button>
                        </a>
                    </div>
                </div> 
                <div className="my-works-content-2">
                    <p className="works-languages">
                    HTML - CSS - JavaScript - React.js
                    </p>
                    <h2 className="works-title">To-Do Today</h2>
                    <p className="works-info">
                    What are your plans for today? Do you have a to-do list and are you afraid 
                    of forgetting something? "To-Do Today" will help you, the application 
                    that allows you to indicate the things to do in the space of a day and to 
                    modify the value at will after completing or canceling it.
                    </p>
                    <div className="works-button-div">
                        <a href="https://todo-today-react.netlify.app">
                            <button className="works-button">Find out more ↘</button>
                        </a>
                    </div>
                </div>  
                <div className="my-works-content-3">
                <p className="works-languages">
                    HTML - CSS - JavaScript
                    </p>
                    <h2 className="works-title">GameSpace</h2>
                    <p className="works-info">
                    Online platform dedicated to gaming. Inside you will find 3 games to 
                    test: "Guess My Number" (guess the random, computer-generated number 
                    between 1 and 20), "Memory Game" (find the matches between the 20 cards 
                    present in the shortest time possible) and "Rock Paper Scissors".
                    </p>
                    <div className="works-button-div">
                        <a href="https://gamespace2023.netlify.app">
                            <button className="works-button">Find out more ↘</button>
                        </a>
                    </div>
                </div>   
            </div>
            <div className="my-works-2">
                <div className="my-works-content-1">
                    <p className="works-languages">
                    HTML - CSS - JavaScript
                    </p>
                    <h2 className="works-title">Guess My Number</h2>
                    <p className="works-info">
                    The game "Guess My Number" consists of guessing a random number between 
                    1 and 20, generated by the computer. The player has a maximum of 20 attempts, 
                    in which he/she is helped by a simple, but useful suggestion ("too low" or 
                    "too high") to arrive at the final solution. 
                    </p>
                    <div className="works-button-div">
                        <a href="https://guess-my-numb3r.netlify.app">
                            <button className="works-button">Find out more ↘</button>
                        </a>
                    </div>
                </div> 
                <div className="my-works-content-2">
                    <p className="works-languages">
                    HTML - CSS - JavaScript
                    </p>
                    <h2 className="works-title">Memory Game</h2>
                    <p className="works-info">
                    The classic "Memory Game" dedicated to one of the most important singing 
                    events in Italy: the "Sanremo Festival". The goal is to find correspondence 
                    between the 20 cards present in the shortest possible time. Each card 
                    features a protagonist from edition 73 of the famous event.
                    </p>
                    <div className="works-button-div">
                        <a href="https://sanremo-2023-memory-game.netlify.app">
                            <button className="works-button">Find out more ↘</button>
                        </a>
                    </div>
                </div>  
                <div className="my-works-content-3">
                <p className="works-languages">
                    HTML - CSS - JavaScript
                    </p>
                    <h2 className="works-title">Rock Paper Scissors</h2>
                    <p className="works-info">
                    The game "Rock Paper Scissors" consists in defeating the opponent by 
                    choosing a sign capable of beating that of the computer, according 
                    to the following rules: the rock breaks the scissors (the rock wins), 
                    the scissors cut the paper (the scissors win) and the paper wraps the 
                    stone (the paper wins). 
                    </p>
                    <div className="works-button-div">
                        <a href="https://rock-paper-scissors-2023.netlify.app">
                            <button className="works-button">Find out more ↘</button>
                        </a>
                    </div>
                </div>   
            </div>
        </section>
    );

}

export default WorksSection; 